### PR TITLE
MacOS Compatibility

### PR DESCRIPTION
**Pull request by giulioz**

### CODE REVIEW

**Comment by yatima1460** [comment]
Nice!

**Comment by yatima1460** [comment]
I wonder if we can use the system headers/calls to get a better raw list and also how to scan samba/network mounted disks too

**Comment by giulioz** [comment]
Not sure about how to do it in MacOS, if you have anything you want to try tell me and I'll test.

Anyways for Mac compatibility there are some library to install first, we should write them in the readme.

**Comment by yatima1460** [comment]
Bear in mind that I've never touched a Mac so I know nothing:

> if you have anything you want to try tell me and I'll test

1. Can you "ls" (ls //NAME/mount or something) samba drives on Mac transparently? Or do you need to use smbclient or other stuff?
I want the cleanest possible way to crawl samba/network drives too
If you can please investigate on a clean way to crawl network drives too!
2. How to create an installer/portable executable for Mac?

> there are some library to install first

If GTK on Mac is a mess then a new configuration with the Darwin GUI libraries is better, I wonder if there are D ports

Also about D dependencies:
I want everything to be added in /vendor, the project needs to compile even without an internet connection and needs to be standalone, and by using a fork of the library so the submodule is in a frozen state

**Pull request merged**
